// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Fe8z9a7Qd1Je4p_iixLSd3_lT00JrLI',
    appId: '1:152953171698:web:e9ae2c13cd6fe99c282a6b',
    messagingSenderId: '152953171698',
    projectId: 'recipe-app-96274',
    authDomain: 'recipe-app-96274.firebaseapp.com',
    storageBucket: 'recipe-app-96274.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmNLV3xCluo4YzqBpnpNCqW-Tk0z4Ax_U',
    appId: '1:152953171698:android:11a3228e963a2d7c282a6b',
    messagingSenderId: '152953171698',
    projectId: 'recipe-app-96274',
    storageBucket: 'recipe-app-96274.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw-EZag6mgAC8Ag8tQy9OrJkjkn4ryIcA',
    appId: '1:152953171698:ios:7b83274f9d3bd280282a6b',
    messagingSenderId: '152953171698',
    projectId: 'recipe-app-96274',
    storageBucket: 'recipe-app-96274.firebasestorage.app',
    iosBundleId: 'com.example.projectApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw-EZag6mgAC8Ag8tQy9OrJkjkn4ryIcA',
    appId: '1:152953171698:ios:7b83274f9d3bd280282a6b',
    messagingSenderId: '152953171698',
    projectId: 'recipe-app-96274',
    storageBucket: 'recipe-app-96274.firebasestorage.app',
    iosBundleId: 'com.example.projectApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-Fe8z9a7Qd1Je4p_iixLSd3_lT00JrLI',
    appId: '1:152953171698:web:3efa1830f665d164282a6b',
    messagingSenderId: '152953171698',
    projectId: 'recipe-app-96274',
    authDomain: 'recipe-app-96274.firebaseapp.com',
    storageBucket: 'recipe-app-96274.firebasestorage.app',
  );

}